### ISSUE TITLE
pre-commit erroneously flags composer as not installed

### ISSUE THREAD

**Issue by webchick** [alexpott/d8githooks#20]
Running through all the instructions in the README, I get stuck at:

```
$ git commit -m "Test."
composer not installed, for instructions visit https://getcomposer.org/
```

And yet...

```
$ composer -V
Composer version 1.4.2 2017-05-17 08:17:52
```

Browsing through the code at https://github.com/alexpott/d8githooks/blob/master/pre-commit-8-4 this seems to result from the output of:

```
# Function to test for command dependencies.
command_exists () {
    type "$1" &> /dev/null ;
}
```

If I manually type that from the command line, I get:

```
$ type "composer"
composer is aliased to `php /usr/local/bin/composer.phar'
```

Any ideas?

**Comment by xjm** [comment]
Have you done a `composer install` in your Drupal repo? That became needed awhile back and may not be reflected in the instructions.

**Comment by webchick** [comment]
Yep.

```
$ pwd
/Users/webchick/Sites/8.x

$ composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
> Drupal\Core\Composer\Composer::preAutoloadDump
> Drupal\Core\Composer\Composer::ensureHtaccess
```

**Comment by webchick** [comment]
Oh, and the `composer install` bit is in the testing copy/pasta instructions in the README, so thanks whoever did that! :D

**Comment by xjm** [comment]
I had to install yarn just now (on 8.4.x) which is a recent change, but the hook still worked thereafter. Which branch did you use for the test commit?

**Comment by webchick** [comment]
Yeah, I had to install yarn too, and doing so successfully cleared that check.

8.4.x:

```
$ git branch
* 8.4.x
```

@cilefen and I are doing some debugging in Slack as well; he asked me to type:

```
$ type composer &> /dev/null;echo $?
0
```

So it seems to be returning the right result, but for some reason the script is confused. Seemingly only on my machine (a brand new macOS Sierra 10.12.5 (16F73) install as of last week). Whee. :P

**Comment by webchick** [comment]
Ah-ha. We figured it out. I had followed some instructions s...o...m...e...w...h...e...r...e... that told me to create a bash alias to /usr/local/bin/composer.phar. Instead, just renamed it to /usr/local/bin/composer, and we're in business now!

@xjm++ @cilefen++

Sorry for the noise!
