### ISSUE TITLE
Consider adding a check for jQuery UI in Drupal 9

### ISSUE THREAD

**Issue by zrpnr** [alexpott/d8githooks#28]
In Drupal 9, some of the jQuery UI source files will be added to core/assets/vendor/jquery.ui
These source files can be minified into the files Drupal loads using a build script added in package.json: `yarn build:jqueryui` or with `yarn build`

see: https://www.drupal.org/project/drupal/issues/3087685

@xjm suggested in [#41](https://www.drupal.org/project/drupal/issues/3087685#comment-13338154) to add a check for the full build now that this directory will have source files and a build step in Drupal 9.

**Comment by wimleers** [comment]
@zrpnr Could you create a pull request for this? :)

**Comment by zrpnr** [comment]
The PR is now merged, closing this issue
